server:
  port: 8080

logging:
  level:
    org:
      springframework: debug

spring:
  output:
    ansi:
      enabled: always
  application:
    name: my-restful-service
  message:
    basename: messages
  datasource:
    url: jdbc:mysql://${API_MYSQL_HOST}:${API_MYSQL_PORT}/${API_DATA_BASE_NAME}?useSSL=false
    #jdbc:mysql://localhost:3306/test
    username: ${API_MYSQL_USER_NAME}
    password: ${API_MYSQL_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
        dialect: org.hibernate.dialect.MariaDB8Dialect
#  security:
#    user:
#      name: username
#      password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"